# -- Base Conf --
baseURL = "https://mdcourse.ir/"
languageCode = "fa-IR"
title = "خانه"
theme = "bookworm-FE"
paginate = "7"

# - Post Url - 
[permalinks]


# This section is only for working aliases properly



# ----- Plugins -----

# -- CSS Plugins --
[[params.plugins.css]]
link = "https://lib.arvancloud.ir/bootstrap/5.3.0-alpha1/css/bootstrap.rtl.min.css"
[[params.plugins.css]]
link = "plugins/line-awesome/css/line-awesome.min.css"
[[params.plugins.css]] # Font Vazir
link = "https://cdn.jsdelivr.net/gh/rastikerdar/vazirmatn@v33.003/Vazirmatn-font-face.css"
[[params.plugins.css]] # Custom Css
link = "plugins/customCss/main.css"
[[params.plugins.css]] # Vanilla Gallery
link = "plugins/Vanilla-Gallery-main/Css-script/RO/Gallery-OCO.css"

# -- JS Plugins --
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "https://lib.arvancloud.ir/jquery/3.6.0/jquery.js"
[[params.plugins.js]]
link = "https://lib.arvancloud.ir/alpinejs/3.9.6/cdn.min.js"
[[params.plugins.js]]
link = "plugins/md-daily/md-daily.js"

# site variables
[params.variables]
font_primary = "Vazirmatn"
h1 = "64px"
h1_lg = "52px"
h1_md = "42px"
h2 = "38px"
h2_md = "30px"
h3 = "30px"
h3_md = "24px"
h4 = "24px"
h5 = "18px"
h6 = "16px"
white = "#ffffff"
black = "#000000"
dark = "#152035"
gray = "#747577"
light = "#FAFAFA"
color_primary = "#01AD9F"

# ----- Theme Parameters -----
[params]

# -- SiteTitle --
SiteTitle = "ام دی کورس"

# -- Comment --
Commentrepo = "mdpe-ir/MdCourse"
Commenttheme = "github-light"
Commentlabel = "کامنت"

# -- Logo and Favicon --
logo = "images/logo.png"
logo_height = "65px"
favicon = "images/favicon.png"

# -- Meta data --
description = "آموزش آزاد و رایگان برای همه"

# -- contact form action --
contact_form_action = "#" # contact form works with https://formspree.io

# -- Main Section --
mainSections = ["blog"]

# -- Footer --
copyright = "تمامی حقوق محفوظ است ، تحت لایسنس [CC](https://creativecommons.org/licenses/by/4.0/)"

# -- counter -- 
[params.counter]
enable = true
user = "mdpe-ir"

# -- Social --

# - telegram -
[[params.social]]
url = "https://t.me/MdDaily"
icon = "lab la-telegram"

# - Github -
[[params.social]]
url = "https://github.com/mdpe-ir/"
icon = "lab la-github"

# ----- Menu -----

# -- Main Menu --

[[menu.main]]
weight = 1
url = "/"
name = "خانه"

[[menu.main]]
weight = 3
url = "about"
name = "درباره"

[[menu.main]]
weight = 4
url = "contact"
name = "ارتباط"

# -- Footer Menu --

[[menu.footer]]
weight = 1
url = "author/"
name = "نویسندگان"

[[menu.footer]]
weight = 2
url = "archive/"
name = "بایگانی"

 [[menu.footer]]
 weight = 3
 url = "privacy/"
 name = "امنیت و حریم خصوصی"
